sudo: required
dist: trusty
language: c++

os:
  - osx
  - linux

compiler:
  - clang

addons:
  apt:
    packages:
    - build-essential
    - autoconf
    - libxml2-dev
    - libxslt1-dev
    - qt5-default

matrix:
  include:
  - osx_image: xcode6.4
  - osx_image: xcode7.3
  - osx_image: xcode8.2
  - os: linux
    compiler: gcc

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt@5.5 && brew link --force qt@5.5 ; fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./autogen.sh ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh build_mac.sh ; fi
